version: "3"

services:
  web:
    environment:
      - CouncilTag=debug
      - DJANGO_SECRET_KEY=examplesecretkeydonotuseinprod
      - RECAPTCHAKEY=some_string
      - DB_NAME=postgres
      - DB_USER=postgres
      - HOST=db
      - REDIS_HOST=redis
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres
  redis:
    image: redis
